/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputCell: typeof import('./src/components/input-cell.vue')['default']
  }
}
